language: node_js
python:
- '3.5'
node_js:
- '8.1'
sudo: required
before_install:
- sudo apt-get update
- rvm install 2.4.8
- rvm use 2.4.8
- sudo update-ca-certificates
- sudo apt-get install libcurl4-openssl-dev
- "./tool/before_install.sh"
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
script: "./tool/travis.sh"
before_deploy:
- echo "Building site..."
- bundle exec jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
  project: daskeyboard-io
  on:
    branch: deploy
env:
  global:
    - secure: h0UCEl3PyIRgY3Z+zkT9OaVWgN0NL/rj/9wPO7grhYn+mpxa0TgQtmGFl6vwODVsi8MWFkIU4WeZQtaFs7aDJRjImaRIdkhgAMZ6FuzIKUwEtPbwTIBhJ4JWXv+bPlbieKs/13A1De2I9BO1sZPZpZcypaAiNl9hX8epHFW46rCLJqgDuz4btQiexFVj5nzhkVcwoOdWOzTOSTm9ysCiMNNkHs0dHVTq99V2eH2f0o3goc1vw9/77n+sMOll6wDyZuqZ85nxTd39dnu8vEcPuMQ6ntdbBwkZBifWSuPwqFxWY+IboSpeb/G+dguw4tWP//G4vJN61FXVg6o0MuiIIWr+VLfQqaW9ic+raGRZjVbIng4OgqicZMK3TlJQ0nhsOdbJ+0VyXJFE5hFKMdzQKGVaxVi9KpLzcUYaF2LZyqZ7VmyHRZVp+ZD74QARBOI/wcdvb1pUYUfEff5gtarnywtk0/NhNBjHhtgmpis45QkWFRGqSVI2X/IpEQHMZUlC3jkKVhCjn0UeLJeyGk9OFtuqDpnOdblfL8ID0QiTxMV2OEhVH4qDVxjgm3sXnpvtehTnjKwFgWk6wSOI75DijCJpm46MdE7jjqFtecTzhmCnxAujEh5We6KSb8qpJODG/TOuWVMY13vRrJlp8oRRjtFbj+UzOzc/GPFqM8DnF5Q=
    - secure: rDdfmV3Lst9zp0HIUMJzMgFsWgA0ouxxrzjvG3vOyz+WYXXkCFZRgCC/4D4k2EBHuiA2cntbzVtY1cQ5fnHxjdb2e0wbgp0ZkHRGmszJfWXzxTIbJDAqXyxsG3K43D1VXg2W/XPa1GigMl3iDmgl4/k40PT/YQI+bTOOL0gBWLol/283X7RJbpBnvESUgzBPECqXzuLSU9WQ2XhFlLEeztdQcrLClalnEz4K1EAKAkoCwn9Q7nUEnjdbWIBeVrMzXMDSpJ1IZl9mpXp62TD6bo4jY/4sUV4hIQJirVgH+HdB0uMiiZXqvrTKGrRh812y06PzcW+R4VBPR8FE0yYlcyw6GZSyIMvvx59Rv5I6TdHk2e+qWWfMhZwkS+EO4i/0kIOnV4fOF0lrsbRqLNLRNRTnlM3X7lZPSOw0dMNFIbKFZUqemFsnw1hzw+nYvA1enEjpnkeUTXhsheUSA1EiWNAbGbtMEtPKPyN2ZNJLo9d4G3Yajffc62fj0xiwd5PDhu5EdLAKa+f+01z1ebR0dsTe5fKoEQBQpLB9lorySE6LW7J4dTwUBQ3KwF7EzFHa6F1uPixxpmMOjTe55pNmWUfmmxHDAZARrj6NdcwAzXWkXkV+jlgNvR2V2/eEyhcuSfpUMQFsRVTve6QuKaX31OCvjl9yjx6h2ksJy2UPoCQ=
    - NODE_GYP_FORCE_PYTHON=python3
