language: node_js
node_js:
- '8.1'
sudo: false
before_install:
- rvm install 2.2.2
- "./tool/before_install.sh"
script: "./tool/travis.sh"
before_deploy:
- echo "Building site."
- bundle exec jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    # secure: WSNKyIYR08tD8mYWCjXI3kXcwSwHtsbSUwiTs5bSa7Q/eymV2dn1jNaUH0QOamc/rL9c10YxPP8EfOTNNPQeLOP89KjkQ2aF3b/BrsuGa9uGJvSNJLm7/rNaj3pJCYiXSYIHTuzvvjNgdhMRdHK0KXOt0HazX5NUAO5ovIWmFXMBysV78+2zEH2+d+8EKvw0PvlZpbd2pvkFAviX6GgIELvqHBCYIsAKhH/vaLOAAiIJh0Ci61rixVXCFXoj4senKei4g0TTI3yZwB4aIE/HvtZxRc0BN+PcZXlL13oyoBmUnvE7t6ZBr3hIZFxzNYnHSJgPg/sUvPc7r+w/PHrrDEET7oNnVzY50X+vox+YxyhnsXykaejJ6aIieE61l/ilegsu2YVBNAimiI74QtB7DK8sUGnVE4NZPyoLGDL29/qLJtKxoI6bX23qin8tT/8huPPycI16ngY/SnnZOSqP5sldkfwf2htI14KYgNPMNa6Me32ZmiBL8A6UFVQgDUFyUUafhYI6YDShP8X2YmqGDPt+haCh0ZILVS2DT/cXXE4p3uwoK5JiWKQMfLGp9QuR92rb8+dsJmSTXBvi7ZQjEXkBOFk02YhjPDC+hs6P8zfoLPm00r8dK/CxVmRddKK6IB9vWtcJ9AaXNpxbE7VZsh3VCJ0DREAmHrYgBIVr8u8=
    secure: inDrMKgzN/ldww3fBptQI1UOurRMZEUMMF3R2m0fcPtfm26UGbvbvW/fiaAsKo9mDsFfu7QoVsBnHNo/Tby0WlV5CX+nktqMG2kBCZPZXY8cZYYQCwIgblDorr9L7Tcfd7zxxb5yIqeaABdzFeA4gmlikynNPt9BLd8vkJY7qYYgEJg6YOlPmUuazxmm99Y2wHx6mssYraVK3m560ruQqnvLuZO8esBavLnIefPpf5Hr8M9Q+GnFveiIZKcbWFbBEPqFOYP2vQqqvmGgfmxxorQU7ZRYU0KGlzT5VVZSCnQSq2HfA5iNi8lvV9daZ9dCrteoNI9AgRjIe6hibrK4DqCMR660TpZyl0xtDy3wSIZKtfpZOW3+koUFNcm/jXIi5rWYHaB8hk6CKoXTg3EWGwwDl6ROFylR5XehG3NHjFldaoPfw9ZHD2HveQfuMSjn1h+f5+EQNygy1oF7NTqGLW9Tae6r7NEgNc73sIGxOy3PayU4rZOdLphg7nMSO0CBc3r8JnA0q0By7ZPAScl9qXDv7zosHKJ5pH3Nz4P90vywmbiuwf1FgJjMxuAK487oleVCofcEFjExoot+r/DKEhzDSKiVlYpEGdMgYs1aYRtY0UpBwOOS6gwBomM+RqgbmfaGqcwwWQy7RVQ9SmI4OxVWAIB0aXCWnpyoC88ZfKk=
  project: daskeyboard-io
