language: node_js
node_js:
- '8.1'
sudo: required
before_install:
- rvm install 2.3.0
- rvm use 2.3.0
- sudo apt-get install libcurl4-openssl-dev
- "./tool/before_install.sh"
script: "./tool/travis.sh"
before_deploy:
- echo "Building site..."
- bundle exec jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: daskeyboard-io
