language: node_js
node_js:
- '8.1'
sudo: false
before_install:
- rvm install 2.2.2
- "./tool/before_install.sh"
script: "./tool/travis.sh"
before_deploy:
- echo "Building site..."
- bundle exec jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: daskeyboard-io
